import 'package:isar/isar.dart';

part 'discovered_road.g.dart'; // This file will be generated by the build_runner

@collection
class DiscoveredRoad {
  Id id = Isar.autoIncrement;

  @Index(unique: true, replace: true)
  late String placeId; // The unique ID from Google Roads API

  late double latitude;
  late double longitude;
}