// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA83qMrv7SIYBxwZx3v0_g7ZOMVK_Kfkko',
    appId: '1:416471692126:web:f9efa8c0388f99216795cf',
    messagingSenderId: '416471692126',
    projectId: 'mapz-public',
    authDomain: 'mapz-public.firebaseapp.com',
    storageBucket: 'mapz-public.firebasestorage.app',
    measurementId: 'G-062WV29YXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVE3M48PFwze57lt-mCiXC5rTJlg72r3w',
    appId: '1:416471692126:android:bf64a0299a732cee6795cf',
    messagingSenderId: '416471692126',
    projectId: 'mapz-public',
    storageBucket: 'mapz-public.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-f9AhfaudH326e5CMcYO9IRbOrqpMGR4',
    appId: '1:416471692126:ios:1657989c543dca0c6795cf',
    messagingSenderId: '416471692126',
    projectId: 'mapz-public',
    storageBucket: 'mapz-public.firebasestorage.app',
    iosBundleId: 'com.example.mapz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-f9AhfaudH326e5CMcYO9IRbOrqpMGR4',
    appId: '1:416471692126:ios:1657989c543dca0c6795cf',
    messagingSenderId: '416471692126',
    projectId: 'mapz-public',
    storageBucket: 'mapz-public.firebasestorage.app',
    iosBundleId: 'com.example.mapz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA83qMrv7SIYBxwZx3v0_g7ZOMVK_Kfkko',
    appId: '1:416471692126:web:5947c3ed359709c86795cf',
    messagingSenderId: '416471692126',
    projectId: 'mapz-public',
    authDomain: 'mapz-public.firebaseapp.com',
    storageBucket: 'mapz-public.firebasestorage.app',
    measurementId: 'G-03VG1GYGT1',
  );
}
